export const FOLLOW_USER = "FOLLOW_USER";
export const UNFOLLOW_USER = "UNFOLLOW_USER";
export const FETCH_FOLLOWS = "FETCH_FOLLOWS";
export const IS_FOLLOWING = "IS_FOLLOWING";
export const FOLLOW_NUMBERS = "FOLLOW_NUMBERS";
export const FETCH_FOLLOWERS = "FETCH_FOLLOWERS";
export const FETCH_FOLLOWINGS = "FETCH_FOLLOWINGS";
