export const CREATE_RECIPE = "CREATE_RECIPE";
export const FETCH_RECIPES = "FETCH_RECIPES";
export const SEARCH_RECIPES = "SEARCH_RECIPES";
export const FETCH_RECIPE = "FETCH_RECIPE";
export const FETCH_USER_RECIPES = "FETCH_USER_RECIPES";
